name: "godot-ci export"
on:
  push:
    branches:
    - master

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: "Source of Mana"
  PROJECT_PATH: "."

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      timestamp: ${{ steps.get-timestamp.outputs.time }}
    steps:
      - name: Get build timestamp
        id: get-timestamp
        run: |
          echo "time=$(/bin/date -u "+%Y-%m-%d-%H%M")" >> $GITHUB_OUTPUT
      - name: Generate environmental variables
        id: generate_env_vars
        run: echo "release_name=Source of Mana experimental build ${{ steps.get-timestamp.outputs.time }}" >> $GITHUB_OUTPUT
  builds:
    needs: release
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          artifact: linux
          export_template: "Linux/X11"
          ext: "x86_64"
        - name: Linux (Headless Server)
          artifact: linux-server-headless
          export_template: "Linux/X11 Headless Server"
        - name: Windows
          artifact: windows
          export_template: "Windows Desktop"
          ext: "exe"
        - name: macOS
          artifact: macos
          export_template: "macOS"
          ext: "zip"
    runs-on: ubuntu-20.04
    permissions: write-all
    container:
      image: barichello/godot-ci:4.3
    name: Export: {{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: {{ matrix.name }} Build
        run: |
          mkdir -v -p "build/{{ matrix.artifact }}"
          cd "$PROJECT_PATH"
          godot --headless --verbose --export-release "{{ matrix.export_template }}" "build/{{ matrix.artifact }}/${EXPORT_NAME}-{{ matrix.artifact }}.${{ matrix.ext }}"
      - run: |
          gh release upload sourceofmana-experimental-${{ needs.release.outputs.timestamp }} "builds/{{ matrix.artifact }}/${EXPORT_NAME}-{{ matrix.artifact }}-${{ needs.release.outputs.timestamp }}.${{ matrix.ext }}"

